# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170102_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
